0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/eunsol/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/eunsol/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/eunsol/Project/quac/allennlp-quac/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/home/eunsol/Project/quac/allennlp-quac/allennlp/commands/__init__.py", line 65, in main
    args.func(args)
  File "/home/eunsol/Project/quac/allennlp-quac/allennlp/commands/train.py", line 99, in train_model_from_args
    args.recover)
  File "/home/eunsol/Project/quac/allennlp-quac/allennlp/commands/train.py", line 129, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/home/eunsol/Project/quac/allennlp-quac/allennlp/commands/train.py", line 266, in train_model
    (instance for key, dataset in all_datasets.items()
  File "/home/eunsol/Project/quac/allennlp-quac/allennlp/data/vocabulary.py", line 384, in from_params
    only_include_pretrained_words=only_include_pretrained_words)
  File "/home/eunsol/Project/quac/allennlp-quac/allennlp/data/vocabulary.py", line 332, in from_instances
    for instance in Tqdm.tqdm(instances):
  File "/home/eunsol/anaconda3/envs/allennlp/lib/python3.6/site-packages/tqdm/_tqdm.py", line 953, in __iter__
    for obj in iterable:
  File "/home/eunsol/Project/quac/allennlp-quac/allennlp/commands/train.py", line 267, in <genexpr>
    for instance in dataset
  File "/home/eunsol/Project/quac/allennlp-quac/allennlp/data/dataset_readers/reading_comprehension/dqa.py", line 62, in _read
    file_path = cached_path(file_path)
  File "/home/eunsol/Project/quac/allennlp-quac/allennlp/common/file_utils.py", line 76, in cached_path
    raise FileNotFoundError("file {} not found".format(url_or_filename))
FileNotFoundError: file /home/my89/dqa/data/train_bits_c2.json not found

